import type { Knex } from 'knex'

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('products', (table) => {
    table.string('id', 100).primary()
    table.string('title', 500).notNullable().defaultTo('')
    table.text('description', 'longtext')
    table.string('coverImage', 1000).defaultTo('')
    table.json('images').nullable()
    table.decimal('price', 10, 2).notNullable().defaultTo(0)
    table.decimal('originalPrice', 10, 2).defaultTo(0)
    table.string('category', 100).defaultTo('')
    table.string('categoryId', 100).defaultTo('')
    table.string('categoryNameSnapshot', 200).defaultTo('')
    table.string('status', 50).notNullable().defaultTo('draft')
    table.string('managerId', 100).defaultTo('')
    table.integer('stock').notNullable().defaultTo(0)
    table.json('options').nullable()
    table.string('publishedBy', 200).defaultTo('')
    table.datetime('publishedAt').nullable()
    table.text('offlineReason')
    table.datetime('offlineAt').nullable()
    table.boolean('requireName').notNullable().defaultTo(false)
    table.boolean('requirePhone').notNullable().defaultTo(false)
    table.datetime('createdAt').notNullable().defaultTo(knex.fn.now())
    table.datetime('updatedAt').notNullable().defaultTo(knex.fn.now())
  })

  await knex.schema.createTable('managers', (table) => {
    table.string('id', 100).primary()
    table.string('username', 200).notNullable()
    table.string('password', 500).notNullable().defaultTo('')
    table.string('name', 200).defaultTo('')
    table.string('phone', 50).defaultTo('')
    table.string('teamName', 200).defaultTo('')
    table.string('status', 50).notNullable().defaultTo('active')
    table.datetime('createdAt').notNullable().defaultTo(knex.fn.now())
    table.datetime('updatedAt').notNullable().defaultTo(knex.fn.now())
  })

  await knex.schema.createTable('users', (table) => {
    table.string('id', 100).primary()
    table.string('phone', 50).defaultTo('')
    table.string('password', 500).notNullable().defaultTo('')
    table.string('nickname', 200).defaultTo('')
    table.string('teamName', 200).defaultTo('')
    table.string('role', 50).notNullable().defaultTo('user')
    table.string('status', 50).notNullable().defaultTo('active')
    table.string('alipayUserId', 200).defaultTo('')
    table.string('wechatOpenId', 200).defaultTo('')
    table.json('loginMethods').nullable()
    table.datetime('createdAt').notNullable().defaultTo(knex.fn.now())
    table.datetime('updatedAt').notNullable().defaultTo(knex.fn.now())
  })

  await knex.schema.createTable('orders', (table) => {
    table.string('id', 100).primary()
    table.string('productId', 100).defaultTo('')
    table.string('userId', 100).defaultTo('')
    table.string('managerId', 100).defaultTo('')
    table.string('employeeId', 100).defaultTo('')
    table.string('productName', 500).defaultTo('')
    table.decimal('productPrice', 10, 2).defaultTo(0)
    table.string('optionLabel', 500).defaultTo('')
    table.string('redirectUrl', 2000).defaultTo('')
    table.string('userName', 200).defaultTo('')
    table.string('userPhone', 50).defaultTo('')
    table.string('teamName', 200).defaultTo('')
    table.string('fundAccount', 200).defaultTo('')
    table.string('status', 50).notNullable().defaultTo('pending')
    table.datetime('reviewedAt').nullable()
    table.text('rejectReason')
    table.datetime('addedToPaymentAt').nullable()
    table.datetime('settledAt').nullable()
    table.string('transferredFromManager', 200).defaultTo('')
    table.datetime('transferredAt').nullable()
    table.string('managedBy', 50).defaultTo('manager')
    table.datetime('createdAt').notNullable().defaultTo(knex.fn.now())
    table.datetime('updatedAt').notNullable().defaultTo(knex.fn.now())
    table.boolean('deleted').defaultTo(false)
    table.datetime('deletedAt').nullable()

    table.index(['deleted'], 'idx_deleted')
    table.index(['deleted', 'managerId'], 'idx_deleted_manager')
    table.index(['deleted', 'status', 'createdAt'], 'idx_deleted_status_createdAt')
    table.index(['deleted', 'managerId', 'status'], 'idx_deleted_managerId_status')
    table.index(['deleted', 'userId', 'status'], 'idx_deleted_userId_status')
    table.index(['deleted', 'employeeId', 'status'], 'idx_deleted_employeeId_status')
    table.index(['userId'], 'idx_userId')
    table.index(['managerId'], 'idx_managerId')
    table.index(['status'], 'idx_status')
    table.index(['createdAt'], 'idx_createdAt')
  })

  await knex.schema.createTable('commissions', (table) => {
    table.string('id', 100).primary()
    table.string('orderId', 100).defaultTo('')
    table.string('userId', 100).defaultTo('')
    table.string('managerId', 100).defaultTo('')
    table.string('productName', 500).defaultTo('')
    table.decimal('amount', 10, 2).defaultTo(0)
    table.string('status', 50).notNullable().defaultTo('pending')
    table.datetime('createdAt').notNullable().defaultTo(knex.fn.now())
    table.datetime('approvedAt').nullable()
    table.datetime('paidAt').nullable()
  })

  await knex.schema.createTable('employees', (table) => {
    table.string('id', 100).primary()
    table.string('userId', 100).notNullable()
    table.string('phone', 50).notNullable()
    table.string('password', 500).notNullable()
    table.string('nickname', 200).defaultTo('')
    table.datetime('expiresAt').notNullable()
    table.string('status', 50).notNullable().defaultTo('active')
    table.datetime('createdAt').notNullable().defaultTo(knex.fn.now())
    table.datetime('updatedAt').notNullable().defaultTo(knex.fn.now())

    table.index(['userId'], 'idx_userId')
    table.index(['phone'], 'idx_phone')
    table.index(['expiresAt'], 'idx_expiresAt')
  })

  await knex.schema.createTable('admins', (table) => {
    table.string('id', 100).primary()
    table.string('phone', 50).notNullable()
    table.string('password', 500).notNullable()
    table.string('name', 200).defaultTo('超级管理员')
    table.string('status', 50).notNullable().defaultTo('active')
    table.datetime('createdAt').notNullable().defaultTo(knex.fn.now())
    table.datetime('updatedAt').notNullable().defaultTo(knex.fn.now())
  })

  await knex.schema.createTable('operation_logs', (table) => {
    table.string('id', 100).primary()
    table.string('adminId', 100).defaultTo('')
    table.string('adminPhone', 50).defaultTo('')
    table.string('adminName', 200).defaultTo('')
    table.string('operationType', 100).notNullable()
    table.string('targetType', 100).notNullable()
    table.string('targetId', 100).defaultTo('')
    table.string('targetName', 500).defaultTo('')
    table.string('reason', 1000).defaultTo('')
    table.text('detail')
    table.datetime('createdAt').notNullable().defaultTo(knex.fn.now())
  })

  await knex.schema.createTable('cart', (table) => {
    table.string('id', 100).primary()
    table.string('userId', 100).notNullable()
    table.string('managerId', 100).defaultTo('')
    table.string('productId', 100).notNullable()
    table.string('productName', 500).defaultTo('')
    table.decimal('productPrice', 10, 2).defaultTo(0)
    table.string('coverImage', 1000).defaultTo('')
    table.string('optionLabel', 500).defaultTo('')
    table.string('redirectUrl', 2000).defaultTo('')
    table.datetime('addedAt').notNullable().defaultTo(knex.fn.now())

    table.index(['userId'], 'idx_userId')
    table.index(['managerId'], 'idx_managerId')
    table.index(['productId'], 'idx_productId')
  })

  await knex.schema.createTable('product_categories', (table) => {
    table.string('id', 100).primary()
    table.string('name', 200).notNullable()
    table.string('value', 200).notNullable()
    table.integer('sort').notNullable().defaultTo(0)
    table.string('status', 50).notNullable().defaultTo('active')
    table.datetime('createdAt').notNullable().defaultTo(knex.fn.now())
    table.datetime('updatedAt').notNullable().defaultTo(knex.fn.now())

    table.index(['status'], 'idx_status')
    table.index(['sort'], 'idx_sort')
  })
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('product_categories')
  await knex.schema.dropTableIfExists('cart')
  await knex.schema.dropTableIfExists('operation_logs')
  await knex.schema.dropTableIfExists('admins')
  await knex.schema.dropTableIfExists('employees')
  await knex.schema.dropTableIfExists('commissions')
  await knex.schema.dropTableIfExists('orders')
  await knex.schema.dropTableIfExists('users')
  await knex.schema.dropTableIfExists('managers')
  await knex.schema.dropTableIfExists('products')
}
